### ISSUE TITLE
[BUG] - Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by LcsGrz** [iran-react-community/rn-dominant-color#12]
When the application is without internet and you try to get the colors you get the native crash on Ios, on android I don't test.

**To Reproduce**
1. Open the app when the internet is off
2. Check the crash on XCode
3. if not, reload the application

**Expected behavior**
Should return a default values without crashing

**Screenshots**
![imagen](https://user-images.githubusercontent.com/21349409/96011603-7f70c400-0e19-11eb-8b48-54bc5553c7f5.png)

**Smartphone:**
 - OS: IOS14

**Additional context**
- react-native: 0.63.3
- rn-dominant-color: 1.7.0

**Comment by mj-iosdev** [comment]
@LcsGrz I was facing the same issue. I updated method for temporary fix

```
    @objc func getColorFromURL(_ imageURL: NSString,callback successCallback: RCTResponseSenderBlock ) {
        if let url = URL(string: imageURL as String) {
            let data = try? Data(contentsOf: url)
            if(data != nil) {
                guard let colors = UIImage(data: data!)?.getColors() else {
                  return successCallback(["#00000000", "#00000000", "#00000000", "#00000000", "#00000000"])
                }
                successCallback([
                  colors.primaryHex,
                  colors.secondaryHex,
                  colors.backgroundHex,
                  colors.detailHex
                ])
            }
        }
    }

```
