### ISSUE TITLE
[BUG] Unable to determine Swift version 

### ISSUE THREAD

**Issue by hasan-li** [iran-react-community/rn-dominant-color#3]
**Describe the bug**
After running `pod install` in ios folder there is an error:

```
[!] Unable to determine Swift version for the following pods:

- `RNDominantColor` does not specify a Swift version and none of the targets (`PROJECT`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

**To Reproduce**
<-- 
1. Go to ios folder
2. run `pod install`
!-->

**Expected behavior**
Installation of rn-dominant-color without errors

**Screenshots**
[https://imgur.com/a/8M1rGGh](url)

**Desktop (please complete the following information):**
 - OS: iOS

**Comment by matinzd** [comment]
Does issue still exist?

**Comment by hasan-li** [comment]
Hey. Yes

**Comment by randowize** [comment]
@hasan-li , SWIFT_VERSION is not configured in this project. Just add an empty Swift file to the project using Xcode and it should fix your  the issue
