### ISSUE TITLE
[BUG] Could not find com.android.support:palette-v7:28.3.1.

### ISSUE THREAD

**Issue by elainework** [iran-react-community/rn-dominant-color#4]
*Description*
I cannot use the package. When I try to build the Android app, I get the error `Could not find com.android.support:palette-v7:28.3.1.`.

**To Reproduce**
1. Add rn-dominant-color to your project.
2. Try to build the app.
3. The build fails with the above error.

**Comment by matinzd** [comment]
Try `npx jetify`
