### ISSUE TITLE
[BUG] RNDominantColor` does not specify a Swift version and none of the targets

### ISSUE THREAD

**Issue by enigmablue** [iran-react-community/rn-dominant-color#6]
Trying to pod install for my RN61.2. Got this error

[!] Unable to determine Swift version for the following pods:

- `RNDominantColor` does not specify a Swift version and none of the targets (`x`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by matinzd** [comment]
Also enable swift in your project by creating a dummy swift file and create bridging headers.
